### ISSUE TITLE
There's no BACK button after entering the coin details

### ISSUE THREAD

**Issue by raven6679** [HODLERTECH/HODLER-Android-App#54]
So if you don't have physical back button ;)

**Comment by HODLERTECH** [comment]
We decided that if more than one person requests the button, it will be placed instead of the "Refresh" button in the upper right corner of the application, and as for refresh (Synchronize), we wonder where to place it, so that it is not visible when it is not needed, and so that it does not obscure anything that is more useful at the moment. Currently, we are most inclined to place it at the bottom of the application in each window, without the option of moving above the opened keyboard. Synchronization is carried out automatically, it also does not have to be highly exposed.

**Comment by raven6679** [comment]
"Back" should be on top-left, not top-right!
