### ISSUE TITLE
Pending status after sending

### ISSUE THREAD

**Issue by raven6679** [HODLERTECH/HODLER-Android-App#57]
There's a small period of time, after sending coins, when balance is untouched (should be "blocked") and there's no pending entry, indicating, that some amount of coins are going to be send.

**Comment by DanielMazurFL4RE** [comment]
You still can do Replace by Fee feature. We can lock it but this is not required since transaction is not stored in blockchain yet, so, you can replace your transaction with bigger fee, this is useful in few cases. 
We can resolve this eg. by adding pending status after receiving confirmation from mempool that tx was accepted (but not confirmed yet) and give an opportunity to user to do a RBF with button under Advanced tab.
