### ISSUE TITLE
Add Custom ETH Token

### ISSUE THREAD

**Issue by HODLERTECH** [HODLERTECH/HODLER-Android-App#6]
Right now user have to add name of the token, short name, decimals and contract address. We should to create our "Tokens Database". Every toked added by user should be placed in our base and the next user who want to add same token should have autofill the form after adding only the full name of the token.

We should to change order of fields to be filled:

Now is: 
1. Contract address
2. Symbol
3. Name
4. Decimals

Should be:
1. Full name:
2. Short name (symbol)
3. Decimals
4. Contract address

IMPORTANT FOR SECURITY: If the auto-fill is available, user should to confirm the contract address by should be confirmed by providing several random characters from the beginning of the contract address.

**Comment by DanielMazurFL4RE** [comment]
Since the most famous database of erc tokens, etherscan.io (Example, EOS https://etherscan.io/address/0x86Fa049857E0209aa7D9e616F7eb3b3B78ECfdb0 ) providing QR Codes, we can add QR reader on the Add ERC20 Token's form. Under "Read Contract" tab on mentioned site we can find important data like decimals place.
