### ISSUE TITLE
ETH & ERC-20 token addresses should have upper/lower-case symbols for validity checks

### ISSUE THREAD

**Issue by n074v41l4bl34u** [HODLERTECH/HODLER-Android-App#61]
ETH & ERC-20 token addresses support additional validity checks using upper/lower-case letters but the app only has lowercase addresses. 

When the address is shared with other software there is no ability to re-check the address for validity and sometimes it produces a warning - MyEtherWallet.com is a one example of such software.

Bitcoin & Litecoin do have mixed-case addresses in the app to support those additional checks.
ETH/token addresses should have them too.

**Comment by DanielMazurFL4RE** [comment]
Yeah, in last time I have noticed that checksumed ETH addresses by case becomes more popular. This feature is not critical (many other software just use canonical lowercase format) but nice-to-have due to avoidance of mistakes while rewriting addresses by a hand. We will include it in future releases

**Comment by n074v41l4bl34u** [comment]
I think they are popular because this functionality is useful, so I'd say it's less of a nice-to-have and more of a should-have feature.

In fact some priority tags like: must-have, should-have, nice-to-have or some other naming-system may be a good way to indicate future direction of development and help triage the inflowing issue requests.
